version: '3.2'
services: 
  api:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: chat.web
    depends_on: 
      - db 
      - rabbit
    environment: 
      - DBDATABASE=chat
      - DBHOST=db
      - DBPASSWORD=Jobsity@2020
      - DBPORT=1433
      - DBUSER=sa
      - ENGINE=mssql
      - RabbitConnectionString="amqp://jobsity:Jobsity2020@rabbit:5672"
    links: 
      - db
      - rabbit
    networks:
      - chat.network
    ports: 
      - "4000:80"
    restart: on-failure

  db:
    container_name: chat.db
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Jobsity@2020"
    image: microsoft/mssql-server-linux:2017-latest
    networks:
      - chat.network
    ports: 
      - "1433:1433"
    restart: on-failure
    volumes:
      - ./volumes/mssql/data:/var/opt/mssql/data
      - ./volumes/mssql/logs:/var/opt/mssql/log
      - ./volumes/mssql/secrets:/var/opt/mssql/secrets

  rabbit:
    container_name: chat.rabbit
    image: rabbitmq:3-management
    environment: 
      RABBITMQ_DEFAULT_USER: jobsity
      RABBITMQ_DEFAULT_PASS: Jobsity2020
    # networks: 
    #   - chat.network
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: on-failure
    volumes: 
      - ./volumes/rabbit:/var/lib/rabbitmq/mnesia

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: chat.worker
    depends_on: 
      - rabbit
    environment: 
      - RabbitConnectionString="amqp://jobsity:Jobsity2020@rabbit:5672"
    links: 
      - rabbit
    networks:
      - chat.network
networks: 
  chat.network: